import type { Quiz } from "@/content/lessons";

export interface TexteComprehension {
  slug: string;
  titre: string;
  matiere: string; // anglais | espagnol | italien
  niveau: string; // 6e ... terminale
  niveauCECRL: string; // A1, A2, B1, B2...
  duree: string;
  resume: string;
  texte: string[]; // paragraphes du texte à lire
  glossaire?: { mot: string; traduction: string }[];
  quiz: Quiz;
}

export const TEXTES_COMPREHENSION: TexteComprehension[] = [
  {
    slug: "ma-famille-comprehension-anglais-6e",
    titre: "My family",
    matiere: "anglais",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur la famille de Lucy et répondre à des questions de compréhension.",
    texte: ["Hello! My name is Lucy. I am eleven years old and I live in London.", "There are four people in my family: my mother, my father, my brother and me. My mother's name is Anna. She is a teacher. My father's name is Paul. He is an engineer.", "My brother's name is Jack. He is fifteen years old and he loves football. I don't like football, I prefer swimming.", "We live in a small house with a garden. We have a dog called Max. He is very friendly!"],
    glossaire: [
      { mot: "eleven", traduction: "onze" },
      { mot: "teacher", traduction: "professeur/enseignant" },
      { mot: "engineer", traduction: "ingénieur" },
      { mot: "friendly", traduction: "gentil/amical" },
    ],
    quiz: {
      slug: "quiz-ma-famille-comprehension-anglais-6e",
      titre: "Quiz — My family",
      questions: [
        {
          id: "q1",
          enonce: "How old is Lucy?",
          choix: ["Ten", "Eleven", "Fifteen", "Twelve"],
          reponse: 1,
          explication: "Le texte dit « I am eleven years old ».",
        },
        {
          id: "q2",
          enonce: "What is Lucy's mother's job?",
          choix: ["Engineer", "Doctor", "Teacher", "Nurse"],
          reponse: 2,
          explication: "Le texte dit « She is a teacher ».",
        },
        {
          id: "q3",
          enonce: "How old is Jack?",
          choix: ["Eleven", "Fourteen", "Fifteen", "Sixteen"],
          reponse: 2,
          explication: "Le texte dit « He is fifteen years old ».",
        },
        {
          id: "q4",
          enonce: "What sport does Lucy prefer?",
          choix: ["Football", "Swimming", "Tennis", "Basketball"],
          reponse: 1,
          explication: "Le texte dit « I prefer swimming ».",
        },
        {
          id: "q5",
          enonce: "What is the name of the family's dog?",
          choix: ["Jack", "Paul", "Max", "Rex"],
          reponse: 2,
          explication: "Le texte dit « We have a dog called Max ».",
        }
      ],
    },
  },
  {
    slug: "une-journee-decole-comprehension-anglais-6e",
    titre: "A day at school",
    matiere: "anglais",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur une journée d'école de Tom et répondre à des questions de compréhension.",
    texte: ["My name is Tom. My school starts at 8.30 in the morning and finishes at 4.30 in the afternoon.", "On Mondays, I have Maths, English and Sport. Maths is my favourite subject because I love numbers!", "At 12 o'clock, I have lunch in the canteen with my friends. We usually eat sandwiches or pasta.", "After school, I do my homework and then I play video games with my brother. I go to bed at 9 pm."],
    glossaire: [
      { mot: "starts", traduction: "commence" },
      { mot: "favourite", traduction: "préféré(e)" },
      { mot: "canteen", traduction: "cantine" },
      { mot: "homework", traduction: "devoirs" },
    ],
    quiz: {
      slug: "quiz-une-journee-decole-comprehension-anglais-6e",
      titre: "Quiz — A day at school",
      questions: [
        {
          id: "q1",
          enonce: "What time does Tom's school start?",
          choix: ["8 o'clock", "8.30", "9 o'clock", "4.30"],
          reponse: 1,
          explication: "Le texte dit « My school starts at 8.30 ».",
        },
        {
          id: "q2",
          enonce: "What is Tom's favourite subject?",
          choix: ["English", "Sport", "Maths", "Art"],
          reponse: 2,
          explication: "Le texte dit « Maths is my favourite subject ».",
        },
        {
          id: "q3",
          enonce: "Where does Tom have lunch?",
          choix: ["At home", "In the canteen", "In the classroom", "In the garden"],
          reponse: 1,
          explication: "Le texte dit « I have lunch in the canteen ».",
        },
        {
          id: "q4",
          enonce: "What does Tom usually eat for lunch?",
          choix: ["Pizza", "Salad", "Sandwiches or pasta", "Soup"],
          reponse: 2,
          explication: "Le texte dit « We usually eat sandwiches or pasta ».",
        },
        {
          id: "q5",
          enonce: "What time does Tom go to bed?",
          choix: ["8 pm", "9 pm", "10 pm", "7 pm"],
          reponse: 1,
          explication: "Le texte dit « I go to bed at 9 pm ».",
        }
      ],
    },
  },
  {
    slug: "ma-maison-comprehension-anglais-6e",
    titre: "My house",
    matiere: "anglais",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur la maison d'Emma et répondre à des questions de compréhension.",
    texte: ["I live in a house with my family. It has two floors. Downstairs, there is a kitchen, a living room and a bathroom.", "Upstairs, there are three bedrooms. My bedroom is small but I love it. There is a bed, a desk and a big window.", "My favourite room is the living room because there is a big sofa and a TV. We watch films together on Fridays.", "Behind the house, there is a garden with a tree. I often play there with my cat, Luna."],
    glossaire: [
      { mot: "downstairs", traduction: "en bas" },
      { mot: "upstairs", traduction: "en haut" },
      { mot: "bedroom", traduction: "chambre" },
      { mot: "behind", traduction: "derrière" },
    ],
    quiz: {
      slug: "quiz-ma-maison-comprehension-anglais-6e",
      titre: "Quiz — My house",
      questions: [
        {
          id: "q1",
          enonce: "How many floors does the house have?",
          choix: ["One", "Two", "Three", "Four"],
          reponse: 1,
          explication: "Le texte dit « It has two floors ».",
        },
        {
          id: "q2",
          enonce: "What room is NOT downstairs?",
          choix: ["Kitchen", "Living room", "Bathroom", "Bedroom"],
          reponse: 3,
          explication: "Les chambres sont en haut (upstairs), pas en bas.",
        },
        {
          id: "q3",
          enonce: "What is in Emma's bedroom?",
          choix: ["A sofa", "A bed, a desk and a window", "A kitchen", "A garden"],
          reponse: 1,
          explication: "Le texte dit « There is a bed, a desk and a big window ».",
        },
        {
          id: "q4",
          enonce: "Why does Emma like the living room?",
          choix: ["There is a big sofa and a TV", "There is a garden", "There is a bed", "There is a kitchen"],
          reponse: 0,
          explication: "Le texte dit « there is a big sofa and a TV ».",
        },
        {
          id: "q5",
          enonce: "What is the name of Emma's cat?",
          choix: ["Max", "Luna", "Tom", "Jack"],
          reponse: 1,
          explication: "Le texte dit « I often play there with my cat, Luna ».",
        }
      ],
    },
  },
  {
    slug: "mon-loisir-prefere-comprehension-anglais-6e",
    titre: "My favourite hobby",
    matiere: "anglais",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur le loisir préféré de Sam et répondre à des questions de compréhension.",
    texte: ["My name is Sam and my favourite hobby is playing the guitar. I started three years ago.", "I practise every day after school, for about thirty minutes. My favourite band is a rock band from London.", "On Saturdays, I have a guitar lesson with my teacher, Mr Brown. He is very patient and funny.", "One day, I want to play in a band with my friends. That would be amazing!"],
    glossaire: [
      { mot: "hobby", traduction: "loisir/passe-temps" },
      { mot: "practise", traduction: "s'entraîner/pratiquer" },
      { mot: "patient", traduction: "patient" },
      { mot: "amazing", traduction: "incroyable" },
    ],
    quiz: {
      slug: "quiz-mon-loisir-prefere-comprehension-anglais-6e",
      titre: "Quiz — My favourite hobby",
      questions: [
        {
          id: "q1",
          enonce: "What is Sam's favourite hobby?",
          choix: ["Swimming", "Playing the guitar", "Playing football", "Reading"],
          reponse: 1,
          explication: "Le texte dit « my favourite hobby is playing the guitar ».",
        },
        {
          id: "q2",
          enonce: "When did Sam start playing the guitar?",
          choix: ["One year ago", "Two years ago", "Three years ago", "Last month"],
          reponse: 2,
          explication: "Le texte dit « I started three years ago ».",
        },
        {
          id: "q3",
          enonce: "How long does Sam practise every day?",
          choix: ["Ten minutes", "Thirty minutes", "One hour", "Two hours"],
          reponse: 1,
          explication: "Le texte dit « for about thirty minutes ».",
        },
        {
          id: "q4",
          enonce: "Who is Sam's guitar teacher?",
          choix: ["Mr Brown", "Mr Smith", "Mrs Green", "Mr Tom"],
          reponse: 0,
          explication: "Le texte dit « my teacher, Mr Brown ».",
        },
        {
          id: "q5",
          enonce: "What does Sam want to do one day?",
          choix: ["Become a teacher", "Play in a band", "Move to London", "Stop playing guitar"],
          reponse: 1,
          explication: "Le texte dit « I want to play in a band with my friends ».",
        }
      ],
    },
  },
  {
    slug: "ma-ville-comprehension-anglais-6e",
    titre: "My town",
    matiere: "anglais",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur la ville de Noah et répondre à des questions de compréhension.",
    texte: ["I live in a small town in the south of England. There are about ten thousand people here.", "In the centre, there is a library, a supermarket and a nice park. I often go to the park with my friends after school.", "There isn't a cinema in my town, but there is one in the next town, twenty minutes away by bus.", "On Saturdays, there is a market in the town square. My mum buys fruit and vegetables there."],
    glossaire: [
      { mot: "town", traduction: "ville (petite)" },
      { mot: "library", traduction: "bibliothèque" },
      { mot: "square", traduction: "place" },
      { mot: "market", traduction: "marché" },
    ],
    quiz: {
      slug: "quiz-ma-ville-comprehension-anglais-6e",
      titre: "Quiz — My town",
      questions: [
        {
          id: "q1",
          enonce: "Where is Noah's town?",
          choix: ["In the north of England", "In the south of England", "In Scotland", "In Wales"],
          reponse: 1,
          explication: "Le texte dit « in the south of England ».",
        },
        {
          id: "q2",
          enonce: "What is NOT in the town centre?",
          choix: ["A library", "A supermarket", "A park", "A cinema"],
          reponse: 3,
          explication: "Le texte dit qu'il n'y a pas de cinéma dans la ville.",
        },
        {
          id: "q3",
          enonce: "How far is the cinema?",
          choix: ["Ten minutes by bus", "Twenty minutes by bus", "One hour by bus", "It's in the town"],
          reponse: 1,
          explication: "Le texte dit « twenty minutes away by bus ».",
        },
        {
          id: "q4",
          enonce: "What happens on Saturdays?",
          choix: ["There is a market", "The park is closed", "There is a football match", "The library is closed"],
          reponse: 0,
          explication: "Le texte dit « there is a market in the town square ».",
        },
        {
          id: "q5",
          enonce: "What does Noah's mum buy at the market?",
          choix: ["Books", "Clothes", "Fruit and vegetables", "Furniture"],
          reponse: 2,
          explication: "Le texte dit « My mum buys fruit and vegetables there ».",
        }
      ],
    },
  },
  {
    slug: "mon-animal-comprehension-anglais-6e",
    titre: "My pet",
    matiere: "anglais",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur l'animal de compagnie de Mia et répondre à des questions de compréhension.",
    texte: ["I have a pet rabbit called Coco. He is white and brown, and he has got very long ears.", "Coco lives in a hutch in the garden, but in the evening, he comes inside the house.", "Every morning, I give him carrots and fresh water. He loves carrots, they are his favourite food!", "Coco is two years old now. He is very calm, but sometimes he likes to run very fast around the garden."],
    glossaire: [
      { mot: "rabbit", traduction: "lapin" },
      { mot: "ears", traduction: "oreilles" },
      { mot: "hutch", traduction: "clapier" },
      { mot: "carrots", traduction: "carottes" },
    ],
    quiz: {
      slug: "quiz-mon-animal-comprehension-anglais-6e",
      titre: "Quiz — My pet",
      questions: [
        {
          id: "q1",
          enonce: "What pet does Mia have?",
          choix: ["A cat", "A dog", "A rabbit", "A bird"],
          reponse: 2,
          explication: "Le texte dit « I have a pet rabbit called Coco ».",
        },
        {
          id: "q2",
          enonce: "What colour is Coco?",
          choix: ["Black and white", "White and brown", "All black", "Grey"],
          reponse: 1,
          explication: "Le texte dit « He is white and brown ».",
        },
        {
          id: "q3",
          enonce: "Where does Coco sleep in the evening?",
          choix: ["In the garden", "Inside the house", "In a hutch outside", "At the neighbour's"],
          reponse: 1,
          explication: "Le texte dit « in the evening, he comes inside the house ».",
        },
        {
          id: "q4",
          enonce: "What is Coco's favourite food?",
          choix: ["Apples", "Carrots", "Bread", "Lettuce"],
          reponse: 1,
          explication: "Le texte dit « He loves carrots, they are his favourite food ».",
        },
        {
          id: "q5",
          enonce: "How old is Coco?",
          choix: ["One year old", "Two years old", "Three years old", "Six months old"],
          reponse: 1,
          explication: "Le texte dit « Coco is two years old now ».",
        }
      ],
    },
  },
  {
    slug: "mi-familia-comprehension-espagnol-6e",
    titre: "Mi familia",
    matiere: "espagnol",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur la famille de Lucía et répondre à des questions de compréhension.",
    texte: ["¡Hola! Me llamo Lucía. Tengo once años y vivo en Madrid.", "En mi familia somos cuatro: mi madre, mi padre, mi hermano y yo. Mi madre se llama Ana. Es profesora. Mi padre se llama Pablo. Es ingeniero.", "Mi hermano se llama Jaime. Tiene quince años y le encanta el fútbol. A mí no me gusta el fútbol, prefiero la natación.", "Vivimos en una casa pequeña con jardín. Tenemos un perro que se llama Max. ¡Es muy simpático!"],
    glossaire: [
      { mot: "once", traduction: "onze" },
      { mot: "profesora", traduction: "professeure" },
      { mot: "ingeniero", traduction: "ingénieur" },
      { mot: "natación", traduction: "natation" },
    ],
    quiz: {
      slug: "quiz-mi-familia-comprehension-espagnol-6e",
      titre: "Quiz — Mi familia",
      questions: [
        {
          id: "q1",
          enonce: "¿Cuántos años tiene Lucía?",
          choix: ["Diez", "Once", "Quince", "Doce"],
          reponse: 1,
          explication: "El texto dice « Tengo once años ».",
        },
        {
          id: "q2",
          enonce: "¿Cuál es la profesión de la madre de Lucía?",
          choix: ["Ingeniera", "Médica", "Profesora", "Enfermera"],
          reponse: 2,
          explication: "El texto dice « Es profesora ».",
        },
        {
          id: "q3",
          enonce: "¿Cuántos años tiene Jaime?",
          choix: ["Once", "Catorce", "Quince", "Dieciséis"],
          reponse: 2,
          explication: "El texto dice « Tiene quince años ».",
        },
        {
          id: "q4",
          enonce: "¿Qué deporte prefiere Lucía?",
          choix: ["Fútbol", "Natación", "Tenis", "Baloncesto"],
          reponse: 1,
          explication: "El texto dice « prefiero la natación ».",
        },
        {
          id: "q5",
          enonce: "¿Cómo se llama el perro de la familia?",
          choix: ["Jaime", "Pablo", "Max", "Rex"],
          reponse: 2,
          explication: "El texto dice « Tenemos un perro que se llama Max ».",
        }
      ],
    },
  },
  {
    slug: "un-dia-de-colegio-comprehension-espagnol-6e",
    titre: "Un día de colegio",
    matiere: "espagnol",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur une journée d'école de Diego et répondre à des questions de compréhension.",
    texte: ["Me llamo Diego. Mi colegio empieza a las ocho y media de la mañana y termina a las cuatro y media de la tarde.", "Los lunes tengo Matemáticas, Inglés y Educación Física. Las matemáticas son mi asignatura favorita porque me encantan los números.", "A las doce, como en el comedor con mis amigos. Normalmente comemos bocadillos o pasta.", "Después del colegio, hago los deberes y luego juego a videojuegos con mi hermano. Me acuesto a las nueve de la noche."],
    glossaire: [
      { mot: "empieza", traduction: "commence" },
      { mot: "asignatura", traduction: "matière scolaire" },
      { mot: "comedor", traduction: "cantine" },
      { mot: "deberes", traduction: "devoirs" },
    ],
    quiz: {
      slug: "quiz-un-dia-de-colegio-comprehension-espagnol-6e",
      titre: "Quiz — Un día de colegio",
      questions: [
        {
          id: "q1",
          enonce: "¿A qué hora empieza el colegio de Diego?",
          choix: ["A las ocho", "A las ocho y media", "A las nueve", "A las cuatro y media"],
          reponse: 1,
          explication: "El texto dice « empieza a las ocho y media ».",
        },
        {
          id: "q2",
          enonce: "¿Cuál es la asignatura favorita de Diego?",
          choix: ["Inglés", "Educación Física", "Matemáticas", "Arte"],
          reponse: 2,
          explication: "El texto dice « Las matemáticas son mi asignatura favorita ».",
        },
        {
          id: "q3",
          enonce: "¿Dónde come Diego?",
          choix: ["En casa", "En el comedor", "En el aula", "En el jardín"],
          reponse: 1,
          explication: "El texto dice « como en el comedor ».",
        },
        {
          id: "q4",
          enonce: "¿Qué come Diego normalmente?",
          choix: ["Pizza", "Ensalada", "Bocadillos o pasta", "Sopa"],
          reponse: 2,
          explication: "El texto dice « comemos bocadillos o pasta ».",
        },
        {
          id: "q5",
          enonce: "¿A qué hora se acuesta Diego?",
          choix: ["A las ocho", "A las nueve", "A las diez", "A las siete"],
          reponse: 1,
          explication: "El texto dice « Me acuesto a las nueve de la noche ».",
        }
      ],
    },
  },
  {
    slug: "mi-casa-comprehension-espagnol-6e",
    titre: "Mi casa",
    matiere: "espagnol",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur la maison d'Elena et répondre à des questions de compréhension.",
    texte: ["Vivo en una casa con mi familia. Tiene dos plantas. Abajo hay una cocina, un salón y un baño.", "Arriba hay tres dormitorios. Mi dormitorio es pequeño pero me encanta. Hay una cama, un escritorio y una ventana grande.", "Mi habitación favorita es el salón porque hay un sofá grande y una televisión. Vemos películas juntos los viernes.", "Detrás de la casa hay un jardín con un árbol. A menudo juego allí con mi gata, Luna."],
    glossaire: [
      { mot: "abajo", traduction: "en bas" },
      { mot: "arriba", traduction: "en haut" },
      { mot: "dormitorio", traduction: "chambre" },
      { mot: "detrás", traduction: "derrière" },
    ],
    quiz: {
      slug: "quiz-mi-casa-comprehension-espagnol-6e",
      titre: "Quiz — Mi casa",
      questions: [
        {
          id: "q1",
          enonce: "¿Cuántas plantas tiene la casa?",
          choix: ["Una", "Dos", "Tres", "Cuatro"],
          reponse: 1,
          explication: "El texto dice « Tiene dos plantas ».",
        },
        {
          id: "q2",
          enonce: "¿Qué habitación NO está abajo?",
          choix: ["Cocina", "Salón", "Baño", "Dormitorio"],
          reponse: 3,
          explication: "Los dormitorios están arriba, no abajo.",
        },
        {
          id: "q3",
          enonce: "¿Qué hay en el dormitorio de Elena?",
          choix: ["Un sofá", "Una cama, un escritorio y una ventana", "Una cocina", "Un jardín"],
          reponse: 1,
          explication: "El texto dice « Hay una cama, un escritorio y una ventana grande ».",
        },
        {
          id: "q4",
          enonce: "¿Por qué le gusta el salón a Elena?",
          choix: ["Hay un sofá grande y una televisión", "Hay un jardín", "Hay una cama", "Hay una cocina"],
          reponse: 0,
          explication: "El texto dice « hay un sofá grande y una televisión ».",
        },
        {
          id: "q5",
          enonce: "¿Cómo se llama la gata de Elena?",
          choix: ["Max", "Luna", "Coco", "Rex"],
          reponse: 1,
          explication: "El texto dice « juego allí con mi gata, Luna ».",
        }
      ],
    },
  },
  {
    slug: "mi-afición-favorita-comprehension-espagnol-6e",
    titre: "Mi afición favorita",
    matiere: "espagnol",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur le loisir préféré de Santi et répondre à des questions de compréhension.",
    texte: ["Me llamo Santi y mi afición favorita es tocar la guitarra. Empecé hace tres años.", "Practico todos los días después del colegio, durante unos treinta minutos. Mi grupo favorito es un grupo de rock de Madrid.", "Los sábados tengo clase de guitarra con mi profesor, el señor Ruiz. Es muy paciente y divertido.", "Algún día quiero tocar en un grupo con mis amigos. ¡Sería increíble!"],
    glossaire: [
      { mot: "afición", traduction: "loisir/passion" },
      { mot: "practico", traduction: "je pratique" },
      { mot: "paciente", traduction: "patient" },
      { mot: "increíble", traduction: "incroyable" },
    ],
    quiz: {
      slug: "quiz-mi-afición-favorita-comprehension-espagnol-6e",
      titre: "Quiz — Mi afición favorita",
      questions: [
        {
          id: "q1",
          enonce: "¿Cuál es la afición favorita de Santi?",
          choix: ["Nadar", "Tocar la guitarra", "Jugar al fútbol", "Leer"],
          reponse: 1,
          explication: "El texto dice « mi afición favorita es tocar la guitarra ».",
        },
        {
          id: "q2",
          enonce: "¿Cuándo empezó Santi a tocar la guitarra?",
          choix: ["Hace un año", "Hace dos años", "Hace tres años", "El mes pasado"],
          reponse: 2,
          explication: "El texto dice « Empecé hace tres años ».",
        },
        {
          id: "q3",
          enonce: "¿Cuánto tiempo practica Santi cada día?",
          choix: ["Diez minutos", "Treinta minutos", "Una hora", "Dos horas"],
          reponse: 1,
          explication: "El texto dice « durante unos treinta minutos ».",
        },
        {
          id: "q4",
          enonce: "¿Quién es el profesor de guitarra de Santi?",
          choix: ["El señor Ruiz", "El señor García", "La señora López", "El señor Pablo"],
          reponse: 0,
          explication: "El texto dice « mi profesor, el señor Ruiz ».",
        },
        {
          id: "q5",
          enonce: "¿Qué quiere hacer Santi algún día?",
          choix: ["Ser profesor", "Tocar en un grupo", "Mudarse a Madrid", "Dejar la guitarra"],
          reponse: 1,
          explication: "El texto dice « quiero tocar en un grupo con mis amigos ».",
        }
      ],
    },
  },
  {
    slug: "mi-ciudad-comprehension-espagnol-6e",
    titre: "Mi ciudad",
    matiere: "espagnol",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur la ville de Nico et répondre à des questions de compréhension.",
    texte: ["Vivo en una ciudad pequeña en el sur de España. Aquí hay unas diez mil personas.", "En el centro hay una biblioteca, un supermercado y un parque bonito. A menudo voy al parque con mis amigos después del colegio.", "No hay cine en mi ciudad, pero hay uno en la ciudad de al lado, a veinte minutos en autobús.", "Los sábados hay un mercado en la plaza. Mi madre compra fruta y verduras allí."],
    glossaire: [
      { mot: "ciudad", traduction: "ville" },
      { mot: "biblioteca", traduction: "bibliothèque" },
      { mot: "plaza", traduction: "place" },
      { mot: "mercado", traduction: "marché" },
    ],
    quiz: {
      slug: "quiz-mi-ciudad-comprehension-espagnol-6e",
      titre: "Quiz — Mi ciudad",
      questions: [
        {
          id: "q1",
          enonce: "¿Dónde está la ciudad de Nico?",
          choix: ["En el norte de España", "En el sur de España", "En Portugal", "En Francia"],
          reponse: 1,
          explication: "El texto dice « en el sur de España ».",
        },
        {
          id: "q2",
          enonce: "¿Qué NO hay en el centro de la ciudad?",
          choix: ["Una biblioteca", "Un supermercado", "Un parque", "Un cine"],
          reponse: 3,
          explication: "El texto dice que no hay cine en la ciudad.",
        },
        {
          id: "q3",
          enonce: "¿A qué distancia está el cine?",
          choix: ["Diez minutos en autobús", "Veinte minutos en autobús", "Una hora en autobús", "Está en la ciudad"],
          reponse: 1,
          explication: "El texto dice « a veinte minutos en autobús ».",
        },
        {
          id: "q4",
          enonce: "¿Qué pasa los sábados?",
          choix: ["Hay un mercado", "El parque está cerrado", "Hay un partido de fútbol", "La biblioteca está cerrada"],
          reponse: 0,
          explication: "El texto dice « hay un mercado en la plaza ».",
        },
        {
          id: "q5",
          enonce: "¿Qué compra la madre de Nico en el mercado?",
          choix: ["Libros", "Ropa", "Fruta y verduras", "Muebles"],
          reponse: 2,
          explication: "El texto dice « Mi madre compra fruta y verduras allí ».",
        }
      ],
    },
  },
  {
    slug: "mi-mascota-comprehension-espagnol-6e",
    titre: "Mi mascota",
    matiere: "espagnol",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur l'animal de compagnie de Marta et répondre à des questions de compréhension.",
    texte: ["Tengo un conejo que se llama Coco. Es blanco y marrón, y tiene las orejas muy largas.", "Coco vive en una conejera en el jardín, pero por la noche entra en casa.", "Cada mañana le doy zanahorias y agua fresca. Le encantan las zanahorias, ¡son su comida favorita!", "Coco tiene dos años ahora. Es muy tranquilo, pero a veces le gusta correr muy rápido por el jardín."],
    glossaire: [
      { mot: "conejo", traduction: "lapin" },
      { mot: "orejas", traduction: "oreilles" },
      { mot: "conejera", traduction: "clapier" },
      { mot: "zanahorias", traduction: "carottes" },
    ],
    quiz: {
      slug: "quiz-mi-mascota-comprehension-espagnol-6e",
      titre: "Quiz — Mi mascota",
      questions: [
        {
          id: "q1",
          enonce: "¿Qué mascota tiene Marta?",
          choix: ["Un gato", "Un perro", "Un conejo", "Un pájaro"],
          reponse: 2,
          explication: "El texto dice « Tengo un conejo que se llama Coco ».",
        },
        {
          id: "q2",
          enonce: "¿De qué color es Coco?",
          choix: ["Negro y blanco", "Blanco y marrón", "Todo negro", "Gris"],
          reponse: 1,
          explication: "El texto dice « Es blanco y marrón ».",
        },
        {
          id: "q3",
          enonce: "¿Dónde duerme Coco por la noche?",
          choix: ["En el jardín", "Dentro de casa", "En una conejera fuera", "En casa del vecino"],
          reponse: 1,
          explication: "El texto dice « por la noche entra en casa ».",
        },
        {
          id: "q4",
          enonce: "¿Cuál es la comida favorita de Coco?",
          choix: ["Manzanas", "Zanahorias", "Pan", "Lechuga"],
          reponse: 1,
          explication: "El texto dice « Le encantan las zanahorias, son su comida favorita ».",
        },
        {
          id: "q5",
          enonce: "¿Cuántos años tiene Coco?",
          choix: ["Un año", "Dos años", "Tres años", "Seis meses"],
          reponse: 1,
          explication: "El texto dice « Coco tiene dos años ahora ».",
        }
      ],
    },
  },
  {
    slug: "la-mia-famiglia-comprehension-italien-6e",
    titre: "La mia famiglia",
    matiere: "italien",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur la famille de Lucia et répondre à des questions de compréhension.",
    texte: ["Ciao! Mi chiamo Lucia. Ho undici anni e vivo a Roma.", "Nella mia famiglia siamo in quattro: mia madre, mio padre, mio fratello e io. Mia madre si chiama Anna. È insegnante. Mio padre si chiama Paolo. È ingegnere.", "Mio fratello si chiama Luca. Ha quindici anni e adora il calcio. A me non piace il calcio, preferisco il nuoto.", "Viviamo in una casa piccola con giardino. Abbiamo un cane che si chiama Max. È molto simpatico!"],
    glossaire: [
      { mot: "undici", traduction: "onze" },
      { mot: "insegnante", traduction: "professeur" },
      { mot: "ingegnere", traduction: "ingénieur" },
      { mot: "nuoto", traduction: "natation" },
    ],
    quiz: {
      slug: "quiz-la-mia-famiglia-comprehension-italien-6e",
      titre: "Quiz — La mia famiglia",
      questions: [
        {
          id: "q1",
          enonce: "Quanti anni ha Lucia?",
          choix: ["Dieci", "Undici", "Quindici", "Dodici"],
          reponse: 1,
          explication: "Il testo dice « Ho undici anni ».",
        },
        {
          id: "q2",
          enonce: "Qual è il lavoro della madre di Lucia?",
          choix: ["Ingegnere", "Medico", "Insegnante", "Infermiera"],
          reponse: 2,
          explication: "Il testo dice « È insegnante ».",
        },
        {
          id: "q3",
          enonce: "Quanti anni ha Luca?",
          choix: ["Undici", "Quattordici", "Quindici", "Sedici"],
          reponse: 2,
          explication: "Il testo dice « Ha quindici anni ».",
        },
        {
          id: "q4",
          enonce: "Quale sport preferisce Lucia?",
          choix: ["Calcio", "Nuoto", "Tennis", "Basket"],
          reponse: 1,
          explication: "Il testo dice « preferisco il nuoto ».",
        },
        {
          id: "q5",
          enonce: "Come si chiama il cane della famiglia?",
          choix: ["Luca", "Paolo", "Max", "Rex"],
          reponse: 2,
          explication: "Il testo dice « Abbiamo un cane che si chiama Max ».",
        }
      ],
    },
  },
  {
    slug: "una-giornata-a-scuola-comprehension-italien-6e",
    titre: "Una giornata a scuola",
    matiere: "italien",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur une journée d'école de Marco et répondre à des questions de compréhension.",
    texte: ["Mi chiamo Marco. La mia scuola inizia alle otto e mezza e finisce alle quattro e mezza.", "Il lunedì ho matematica, inglese ed educazione fisica. La matematica è la mia materia preferita perché adoro i numeri!", "Alle dodici, mangio in mensa con i miei amici. Di solito mangiamo panini o pasta.", "Dopo la scuola, faccio i compiti e poi gioco ai videogiochi con mio fratello. Vado a letto alle nove di sera."],
    glossaire: [
      { mot: "inizia", traduction: "commence" },
      { mot: "materia", traduction: "matière scolaire" },
      { mot: "mensa", traduction: "cantine" },
      { mot: "compiti", traduction: "devoirs" },
    ],
    quiz: {
      slug: "quiz-una-giornata-a-scuola-comprehension-italien-6e",
      titre: "Quiz — Una giornata a scuola",
      questions: [
        {
          id: "q1",
          enonce: "A che ora inizia la scuola di Marco?",
          choix: ["Alle otto", "Alle otto e mezza", "Alle nove", "Alle quattro e mezza"],
          reponse: 1,
          explication: "Il testo dice « inizia alle otto e mezza ».",
        },
        {
          id: "q2",
          enonce: "Qual è la materia preferita di Marco?",
          choix: ["Inglese", "Educazione fisica", "Matematica", "Arte"],
          reponse: 2,
          explication: "Il testo dice « La matematica è la mia materia preferita ».",
        },
        {
          id: "q3",
          enonce: "Dove mangia Marco?",
          choix: ["A casa", "In mensa", "In classe", "In giardino"],
          reponse: 1,
          explication: "Il testo dice « mangio in mensa ».",
        },
        {
          id: "q4",
          enonce: "Cosa mangia di solito Marco?",
          choix: ["Pizza", "Insalata", "Panini o pasta", "Zuppa"],
          reponse: 2,
          explication: "Il testo dice « mangiamo panini o pasta ».",
        },
        {
          id: "q5",
          enonce: "A che ora va a letto Marco?",
          choix: ["Alle otto", "Alle nove", "Alle dieci", "Alle sette"],
          reponse: 1,
          explication: "Il testo dice « Vado a letto alle nove di sera ».",
        }
      ],
    },
  },
  {
    slug: "la-mia-casa-comprehension-italien-6e",
    titre: "La mia casa",
    matiere: "italien",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur la maison d'Elena et répondre à des questions de compréhension.",
    texte: ["Vivo in una casa con la mia famiglia. Ha due piani. Al piano di sotto ci sono una cucina, un soggiorno e un bagno.", "Al piano di sopra ci sono tre camere. La mia camera è piccola ma la adoro. C'è un letto, una scrivania e una grande finestra.", "La mia stanza preferita è il soggiorno perché c'è un grande divano e una televisione. Guardiamo film insieme il venerdì.", "Dietro la casa c'è un giardino con un albero. Gioco spesso lì con la mia gatta, Luna."],
    glossaire: [
      { mot: "piano di sotto", traduction: "en bas" },
      { mot: "piano di sopra", traduction: "en haut" },
      { mot: "camera", traduction: "chambre" },
      { mot: "dietro", traduction: "derrière" },
    ],
    quiz: {
      slug: "quiz-la-mia-casa-comprehension-italien-6e",
      titre: "Quiz — La mia casa",
      questions: [
        {
          id: "q1",
          enonce: "Quanti piani ha la casa?",
          choix: ["Uno", "Due", "Tre", "Quattro"],
          reponse: 1,
          explication: "Il testo dice « Ha due piani ».",
        },
        {
          id: "q2",
          enonce: "Quale stanza NON è al piano di sotto?",
          choix: ["Cucina", "Soggiorno", "Bagno", "Camera"],
          reponse: 3,
          explication: "Le camere sono al piano di sopra, non di sotto.",
        },
        {
          id: "q3",
          enonce: "Cosa c'è nella camera di Elena?",
          choix: ["Un divano", "Un letto, una scrivania e una finestra", "Una cucina", "Un giardino"],
          reponse: 1,
          explication: "Il testo dice « C'è un letto, una scrivania e una grande finestra ».",
        },
        {
          id: "q4",
          enonce: "Perché a Elena piace il soggiorno?",
          choix: ["C'è un grande divano e una televisione", "C'è un giardino", "C'è un letto", "C'è una cucina"],
          reponse: 0,
          explication: "Il testo dice « c'è un grande divano e una televisione ».",
        },
        {
          id: "q5",
          enonce: "Come si chiama la gatta di Elena?",
          choix: ["Max", "Luna", "Coco", "Rex"],
          reponse: 1,
          explication: "Il testo dice « la mia gatta, Luna ».",
        }
      ],
    },
  },
  {
    slug: "il-mio-passatempo-preferito-comprehension-italien-6e",
    titre: "Il mio passatempo preferito",
    matiere: "italien",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur le loisir préféré de Sara et répondre à des questions de compréhension.",
    texte: ["Mi chiamo Sara e il mio passatempo preferito è suonare la chitarra. Ho iniziato tre anni fa.", "Mi esercito ogni giorno dopo la scuola, per circa trenta minuti. Il mio gruppo preferito è un gruppo rock di Roma.", "Il sabato ho lezione di chitarra con il mio insegnante, il signor Bruni. È molto paziente e divertente.", "Un giorno voglio suonare in un gruppo con i miei amici. Sarebbe fantastico!"],
    glossaire: [
      { mot: "passatempo", traduction: "loisir/passe-temps" },
      { mot: "mi esercito", traduction: "je m'entraîne" },
      { mot: "paziente", traduction: "patient" },
      { mot: "fantastico", traduction: "fantastique" },
    ],
    quiz: {
      slug: "quiz-il-mio-passatempo-preferito-comprehension-italien-6e",
      titre: "Quiz — Il mio passatempo preferito",
      questions: [
        {
          id: "q1",
          enonce: "Qual è il passatempo preferito di Sara?",
          choix: ["Nuotare", "Suonare la chitarra", "Giocare a calcio", "Leggere"],
          reponse: 1,
          explication: "Il testo dice « il mio passatempo preferito è suonare la chitarra ».",
        },
        {
          id: "q2",
          enonce: "Quando ha iniziato Sara a suonare la chitarra?",
          choix: ["Un anno fa", "Due anni fa", "Tre anni fa", "Il mese scorso"],
          reponse: 2,
          explication: "Il testo dice « Ho iniziato tre anni fa ».",
        },
        {
          id: "q3",
          enonce: "Quanto tempo si esercita Sara ogni giorno?",
          choix: ["Dieci minuti", "Trenta minuti", "Un'ora", "Due ore"],
          reponse: 1,
          explication: "Il testo dice « per circa trenta minuti ».",
        },
        {
          id: "q4",
          enonce: "Chi è l'insegnante di chitarra di Sara?",
          choix: ["Il signor Bruni", "Il signor Rossi", "La signora Verdi", "Il signor Paolo"],
          reponse: 0,
          explication: "Il testo dice « il mio insegnante, il signor Bruni ».",
        },
        {
          id: "q5",
          enonce: "Cosa vuole fare Sara un giorno?",
          choix: ["Diventare insegnante", "Suonare in un gruppo", "Trasferirsi a Roma", "Smettere di suonare"],
          reponse: 1,
          explication: "Il testo dice « voglio suonare in un gruppo con i miei amici ».",
        }
      ],
    },
  },
  {
    slug: "la-mia-citta-comprehension-italien-6e",
    titre: "La mia città",
    matiere: "italien",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur la ville de Nico et répondre à des questions de compréhension.",
    texte: ["Vivo in una piccola città nel sud dell'Italia. Qui ci sono circa diecimila persone.", "Nel centro ci sono una biblioteca, un supermercato e un bel parco. Vado spesso al parco con i miei amici dopo la scuola.", "Non c'è un cinema nella mia città, ma ce n'è uno nella città vicina, a venti minuti in autobus.", "Il sabato c'è un mercato in piazza. Mia madre compra frutta e verdura lì."],
    glossaire: [
      { mot: "città", traduction: "ville" },
      { mot: "biblioteca", traduction: "bibliothèque" },
      { mot: "piazza", traduction: "place" },
      { mot: "mercato", traduction: "marché" },
    ],
    quiz: {
      slug: "quiz-la-mia-citta-comprehension-italien-6e",
      titre: "Quiz — La mia città",
      questions: [
        {
          id: "q1",
          enonce: "Dove si trova la città di Nico?",
          choix: ["Nel nord dell'Italia", "Nel sud dell'Italia", "In Francia", "In Spagna"],
          reponse: 1,
          explication: "Il testo dice « nel sud dell'Italia ».",
        },
        {
          id: "q2",
          enonce: "Cosa NON c'è nel centro della città?",
          choix: ["Una biblioteca", "Un supermercato", "Un parco", "Un cinema"],
          reponse: 3,
          explication: "Il testo dice che non c'è un cinema nella città.",
        },
        {
          id: "q3",
          enonce: "A che distanza è il cinema?",
          choix: ["Dieci minuti in autobus", "Venti minuti in autobus", "Un'ora in autobus", "È in città"],
          reponse: 1,
          explication: "Il testo dice « a venti minuti in autobus ».",
        },
        {
          id: "q4",
          enonce: "Cosa succede il sabato?",
          choix: ["C'è un mercato", "Il parco è chiuso", "C'è una partita di calcio", "La biblioteca è chiusa"],
          reponse: 0,
          explication: "Il testo dice « c'è un mercato in piazza ».",
        },
        {
          id: "q5",
          enonce: "Cosa compra la madre di Nico al mercato?",
          choix: ["Libri", "Vestiti", "Frutta e verdura", "Mobili"],
          reponse: 2,
          explication: "Il testo dice « Mia madre compra frutta e verdura lì ».",
        }
      ],
    },
  },
  {
    slug: "il-mio-animale-comprehension-italien-6e",
    titre: "Il mio animale",
    matiere: "italien",
    niveau: "6e",
    niveauCECRL: "A1",
    duree: "15 min",
    resume: "Lire un texte court sur l'animal de compagnie de Marta et répondre à des questions de compréhension.",
    texte: ["Ho un coniglio che si chiama Coco. È bianco e marrone, e ha le orecchie molto lunghe.", "Coco vive in una conigliera in giardino, ma la sera entra in casa.", "Ogni mattina gli do carote e acqua fresca. Adora le carote, sono il suo cibo preferito!", "Coco ha due anni ora. È molto tranquillo, ma a volte gli piace correre molto velocemente in giardino."],
    glossaire: [
      { mot: "coniglio", traduction: "lapin" },
      { mot: "orecchie", traduction: "oreilles" },
      { mot: "conigliera", traduction: "clapier" },
      { mot: "carote", traduction: "carottes" },
    ],
    quiz: {
      slug: "quiz-il-mio-animale-comprehension-italien-6e",
      titre: "Quiz — Il mio animale",
      questions: [
        {
          id: "q1",
          enonce: "Che animale ha Marta?",
          choix: ["Un gatto", "Un cane", "Un coniglio", "Un uccello"],
          reponse: 2,
          explication: "Il testo dice « Ho un coniglio che si chiama Coco ».",
        },
        {
          id: "q2",
          enonce: "Di che colore è Coco?",
          choix: ["Nero e bianco", "Bianco e marrone", "Tutto nero", "Grigio"],
          reponse: 1,
          explication: "Il testo dice « È bianco e marrone ».",
        },
        {
          id: "q3",
          enonce: "Dove dorme Coco la sera?",
          choix: ["In giardino", "Dentro casa", "In una conigliera fuori", "Dal vicino"],
          reponse: 1,
          explication: "Il testo dice « la sera entra in casa ».",
        },
        {
          id: "q4",
          enonce: "Qual è il cibo preferito di Coco?",
          choix: ["Mele", "Carote", "Pane", "Lattuga"],
          reponse: 1,
          explication: "Il testo dice « Adora le carote, sono il suo cibo preferito ».",
        },
        {
          id: "q5",
          enonce: "Quanti anni ha Coco?",
          choix: ["Un anno", "Due anni", "Tre anni", "Sei mesi"],
          reponse: 1,
          explication: "Il testo dice « Coco ha due anni ora ».",
        }
      ],
    },
  }
];

export function textesComprehension(matiere: string, niveau: string) {
  return TEXTES_COMPREHENSION.filter((t) => t.matiere === matiere && t.niveau === niveau);
}

export function texteComprehensionBySlug(slug: string) {
  return TEXTES_COMPREHENSION.find((t) => t.slug === slug);
}
