export interface TexteTraduction {
  slug: string;
  titre: string;
  matiere: string; // anglais | espagnol | italien
  niveau: string; // 5e ... terminale
  niveauCECRL: string; // A1, A2, B1, B2...
  duree: string;
  resume: string;
  texteFR: string[]; // texte français — support du thème (français → langue)
  texteLangue: string[]; // texte en langue étrangère — support de la version (langue → français)
  vocabulaireAide?: { mot: string; traduction: string }[];
  pointsAttention?: string[]; // conseils de traduction (faux-amis, structures particulières)
}

export const TEXTES_TRADUCTION: TexteTraduction[] = [
  {
    slug: "journee-ecole-traduction-anglais-5e",
    titre: "Une journée d'école / A school day",
    matiere: "anglais",
    niveau: "5e",
    niveauCECRL: "A2",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur la routine scolaire, dans les deux sens (thème et version).",
    texteFR: ["Tous les matins, Lucas se lève à sept heures et prend son petit-déjeuner en famille.", "Il part au collège à vélo avec son ami Tom, qui habite juste à côté de chez lui.", "Les cours commencent à huit heures et demie et se terminent à seize heures trente.", "Après les cours, Lucas fait ses devoirs puis joue au football avec ses camarades."],
    texteLangue: ["Every morning, Lucas gets up at seven o'clock and has breakfast with his family.", "He goes to school by bike with his friend Tom, who lives right next to his house.", "Lessons start at half past eight and finish at half past four.", "After school, Lucas does his homework and then plays football with his classmates."],
    vocabulaireAide: [{ mot: "se lever", traduction: "to get up" }, { mot: "le petit-déjeuner", traduction: "breakfast" }, { mot: "à vélo", traduction: "by bike" }, { mot: "les devoirs", traduction: "homework" }, { mot: "les camarades", traduction: "classmates" }],
    pointsAttention: ["Attention à l'ordre des mots : en anglais, l'heure se dit « at seven o'clock », le complément de temps se place après le verbe.", "« Faire ses devoirs » se traduit par « to do homework », et non par une traduction littérale de « faire »."],
  },
  {
    slug: "weekend-famille-traduction-anglais-5e",
    titre: "Le week-end en famille / The weekend with family",
    matiere: "anglais",
    niveau: "5e",
    niveauCECRL: "A2",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur les activités du week-end en famille.",
    texteFR: ["Le samedi matin, la famille de Léa va souvent au marché pour acheter des fruits et des légumes.", "L'après-midi, ils font parfois une promenade dans le parc ou rendent visite à leurs grands-parents.", "Le dimanche, toute la famille se retrouve autour d'un grand déjeuner préparé par la mère de Léa.", "Après le repas, Léa aide sa petite sœur à ranger sa chambre avant de regarder un film ensemble."],
    texteLangue: ["On Saturday morning, Léa's family often goes to the market to buy fruit and vegetables.", "In the afternoon, they sometimes go for a walk in the park or visit their grandparents.", "On Sunday, the whole family gets together for a big lunch prepared by Léa's mother.", "After the meal, Léa helps her little sister tidy her room before watching a film together."],
    vocabulaireAide: [{ mot: "le marché", traduction: "the market" }, { mot: "faire une promenade", traduction: "to go for a walk" }, { mot: "les grands-parents", traduction: "grandparents" }, { mot: "ranger", traduction: "to tidy" }, { mot: "le repas", traduction: "the meal" }],
    pointsAttention: ["« Rendre visite à quelqu'un » se traduit par « to visit somebody », sans préposition supplémentaire en anglais.", "Les jours de la semaine prennent une majuscule en anglais : Saturday, Sunday."],
  },
  {
    slug: "vacances-ete-traduction-anglais-5e",
    titre: "Mes vacances d'été / My summer holidays",
    matiere: "anglais",
    niveau: "5e",
    niveauCECRL: "A2",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte au passé sur des vacances d'été.",
    texteFR: ["L'été dernier, je suis parti en vacances avec mes parents au bord de la mer, en Bretagne.", "Nous avons loué une petite maison près de la plage et j'ai appris à faire du surf.", "Un jour, il a beaucoup plu, alors nous avons visité un musée dans la ville voisine.", "Ces vacances resteront un très bon souvenir, surtout à cause des couchers de soleil sur l'océan."],
    texteLangue: ["Last summer, I went on holiday with my parents to the seaside, in Brittany.", "We rented a small house near the beach and I learnt how to surf.", "One day, it rained a lot, so we visited a museum in the nearby town.", "These holidays will remain a great memory, especially because of the sunsets over the ocean."],
    vocabulaireAide: [{ mot: "au bord de la mer", traduction: "at the seaside" }, { mot: "louer", traduction: "to rent" }, { mot: "apprendre à", traduction: "to learn how to" }, { mot: "il a plu", traduction: "it rained" }, { mot: "le coucher de soleil", traduction: "the sunset" }],
    pointsAttention: ["Le passé simple français se traduit ici par le prétérit anglais : « je suis parti » → « I went ».", "« Il a plu » (verbe impersonnel) se traduit par « it rained », avec le sujet « it » obligatoire en anglais."],
  },
  {
    slug: "dia-colegio-traduccion-espagnol-5e",
    titre: "Un día en el colegio / Une journée au collège",
    matiere: "espagnol",
    niveau: "5e",
    niveauCECRL: "A2",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur la routine scolaire, dans les deux sens (thème et version).",
    texteFR: ["Todos los días, Marta se levanta a las siete y desayuna con su familia antes de salir.", "Va al colegio en autobús con su amiga Sofía, que vive en el mismo barrio que ella.", "Las clases empiezan a las ocho y media y terminan a las cuatro y media de la tarde.", "Después de las clases, Marta hace los deberes y luego juega al baloncesto con sus compañeros."],
    texteLangue: ["Tous les jours, Marta se lève à sept heures et prend son petit-déjeuner en famille avant de partir.", "Elle va au collège en bus avec son amie Sofía, qui habite le même quartier qu'elle.", "Les cours commencent à huit heures et demie et se terminent à seize heures trente.", "Après les cours, Marta fait ses devoirs puis joue au basket avec ses camarades."],
    vocabulaireAide: [{ mot: "levantarse", traduction: "se lever" }, { mot: "desayunar", traduction: "prendre le petit-déjeuner" }, { mot: "el barrio", traduction: "le quartier" }, { mot: "los deberes", traduction: "les devoirs" }, { mot: "los compañeros", traduction: "les camarades" }],
    pointsAttention: ["Le verbe pronominal « levantarse » s'accorde avec le sujet : « me levanto, te levantas, se levanta ».", "En espagnol, l'heure s'exprime avec « a las » : « a las siete » (à sept heures)."],
  },
  {
    slug: "fin-semana-familia-traduccion-espagnol-5e",
    titre: "El fin de semana en familia / Le week-end en famille",
    matiere: "espagnol",
    niveau: "5e",
    niveauCECRL: "A2",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur les activités du week-end en famille.",
    texteFR: ["Los sábados por la mañana, la familia de Pablo suele ir al mercado para comprar fruta y verdura.", "Por la tarde, a veces dan un paseo por el parque o visitan a sus abuelos.", "Los domingos, toda la familia se reúne para una gran comida preparada por la madre de Pablo.", "Después de comer, Pablo ayuda a su hermana pequeña a ordenar su habitación antes de ver una película juntos."],
    texteLangue: ["Le samedi matin, la famille de Pablo va souvent au marché pour acheter des fruits et des légumes.", "L'après-midi, ils font parfois une promenade dans le parc ou rendent visite à leurs grands-parents.", "Le dimanche, toute la famille se retrouve pour un grand repas préparé par la mère de Pablo.", "Après le repas, Pablo aide sa petite sœur à ranger sa chambre avant de regarder un film ensemble."],
    vocabulaireAide: [{ mot: "el mercado", traduction: "le marché" }, { mot: "dar un paseo", traduction: "faire une promenade" }, { mot: "los abuelos", traduction: "les grands-parents" }, { mot: "ordenar", traduction: "ranger" }, { mot: "la comida", traduction: "le repas" }],
    pointsAttention: ["« Soler + infinitif » exprime une habitude en espagnol : « suele ir » = « il/elle a l'habitude d'aller, va souvent ».", "Attention au faux-ami : « comida » signifie « repas » ou « déjeuner », pas seulement « nourriture »."],
  },
  {
    slug: "vacaciones-verano-traduccion-espagnol-5e",
    titre: "Mis vacaciones de verano / Mes vacances d'été",
    matiere: "espagnol",
    niveau: "5e",
    niveauCECRL: "A2",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte au passé sur des vacances d'été.",
    texteFR: ["El verano pasado, fui de vacaciones con mis padres a la costa, en Galicia.", "Alquilamos una casita cerca de la playa y aprendí a hacer surf.", "Un día llovió mucho, así que visitamos un museo en el pueblo vecino.", "Esas vacaciones serán un recuerdo muy bonito, sobre todo por las puestas de sol sobre el océano."],
    texteLangue: ["L'été dernier, je suis parti en vacances avec mes parents sur la côte, en Galice.", "Nous avons loué une petite maison près de la plage et j'ai appris à faire du surf.", "Un jour, il a beaucoup plu, alors nous avons visité un musée dans le village voisin.", "Ces vacances resteront un très joli souvenir, surtout à cause des couchers de soleil sur l'océan."],
    vocabulaireAide: [{ mot: "la costa", traduction: "la côte" }, { mot: "alquilar", traduction: "louer" }, { mot: "aprender a", traduction: "apprendre à" }, { mot: "llovió", traduction: "il a plu" }, { mot: "la puesta de sol", traduction: "le coucher de soleil" }],
    pointsAttention: ["Le prétérit espagnol (« fui », « llovió ») correspond au passé composé/passé simple français pour raconter des faits passés terminés.", "« Llovió » est une forme impersonnelle : pas de sujet exprimé, contrairement au français « il a plu »."],
  },
  {
    slug: "giornata-scuola-traduzione-italien-5e",
    titre: "Una giornata a scuola / Une journée à l'école",
    matiere: "italien",
    niveau: "5e",
    niveauCECRL: "A2",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur la routine scolaire, dans les deux sens (thème et version).",
    texteFR: ["Ogni mattina, Giulia si alza alle sette e fa colazione con la sua famiglia prima di uscire.", "Va a scuola in autobus con la sua amica Sara, che abita nello stesso quartiere.", "Le lezioni cominciano alle otto e mezza e finiscono alle quattro e mezza del pomeriggio.", "Dopo le lezioni, Giulia fa i compiti e poi gioca a pallavolo con i suoi compagni."],
    texteLangue: ["Tous les matins, Giulia se lève à sept heures et prend son petit-déjeuner en famille avant de sortir.", "Elle va à l'école en bus avec son amie Sara, qui habite dans le même quartier.", "Les cours commencent à huit heures et demie et se terminent à seize heures trente.", "Après les cours, Giulia fait ses devoirs puis joue au volley-ball avec ses camarades."],
    vocabulaireAide: [{ mot: "alzarsi", traduction: "se lever" }, { mot: "fare colazione", traduction: "prendre le petit-déjeuner" }, { mot: "il quartiere", traduction: "le quartier" }, { mot: "i compiti", traduction: "les devoirs" }, { mot: "i compagni", traduction: "les camarades" }],
    pointsAttention: ["Le verbe pronominal « alzarsi » s'accorde avec le sujet : « mi alzo, ti alzi, si alza ».", "En italien, l'heure s'exprime avec « alle » : « alle sette » (à sept heures)."],
  },
  {
    slug: "weekend-famiglia-traduzione-italien-5e",
    titre: "Il fine settimana in famiglia / Le week-end en famille",
    matiere: "italien",
    niveau: "5e",
    niveauCECRL: "A2",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur les activités du week-end en famille.",
    texteFR: ["Il sabato mattina, la famiglia di Marco va spesso al mercato per comprare frutta e verdura.", "Il pomeriggio, a volte fanno una passeggiata al parco o vanno a trovare i nonni.", "La domenica, tutta la famiglia si riunisce per un grande pranzo preparato dalla madre di Marco.", "Dopo il pranzo, Marco aiuta la sorellina a mettere in ordine la sua camera prima di guardare un film insieme."],
    texteLangue: ["Le samedi matin, la famille de Marco va souvent au marché pour acheter des fruits et des légumes.", "L'après-midi, ils font parfois une promenade au parc ou rendent visite à leurs grands-parents.", "Le dimanche, toute la famille se retrouve pour un grand déjeuner préparé par la mère de Marco.", "Après le déjeuner, Marco aide sa petite sœur à ranger sa chambre avant de regarder un film ensemble."],
    vocabulaireAide: [{ mot: "il mercato", traduction: "le marché" }, { mot: "fare una passeggiata", traduction: "faire une promenade" }, { mot: "i nonni", traduction: "les grands-parents" }, { mot: "mettere in ordine", traduction: "ranger" }, { mot: "il pranzo", traduction: "le déjeuner" }],
    pointsAttention: ["« Andare a trovare qualcuno » signifie « rendre visite à quelqu'un », littéralement « aller trouver ».", "Attention au faux-ami : « camera » signifie « chambre » en italien, pas « appareil photo »."],
  },
  {
    slug: "vacanze-estive-traduzione-italien-5e",
    titre: "Le mie vacanze estive / Mes vacances d'été",
    matiere: "italien",
    niveau: "5e",
    niveauCECRL: "A2",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte au passé sur des vacances d'été.",
    texteFR: ["La scorsa estate, sono andato in vacanza con i miei genitori al mare, in Sardegna.", "Abbiamo affittato una casetta vicino alla spiaggia e ho imparato a fare surf.", "Un giorno ha piovuto molto, così abbiamo visitato un museo nel paese vicino.", "Quelle vacanze resteranno un bellissimo ricordo, soprattutto per i tramonti sull'oceano."],
    texteLangue: ["L'été dernier, je suis parti en vacances avec mes parents à la mer, en Sardaigne.", "Nous avons loué une petite maison près de la plage et j'ai appris à faire du surf.", "Un jour, il a beaucoup plu, alors nous avons visité un musée dans le village voisin.", "Ces vacances resteront un très beau souvenir, surtout à cause des couchers de soleil sur l'océan."],
    vocabulaireAide: [{ mot: "il mare", traduction: "la mer" }, { mot: "affittare", traduction: "louer" }, { mot: "imparare a", traduction: "apprendre à" }, { mot: "ha piovuto", traduction: "il a plu" }, { mot: "il tramonto", traduction: "le coucher de soleil" }],
    pointsAttention: ["Le passé composé italien (« sono andato », « ho imparato ») correspond au passé composé français ; attention au choix de l'auxiliaire (essere/avere).", "« Ha piovuto » est une forme impersonnelle sans sujet exprimé, comme en français « il a plu »."],
  },
  {
    slug: "entretien-travail-traduction-anglais-4e",
    titre: "Un entretien pour un job d'été / A summer job interview",
    matiere: "anglais",
    niveau: "4e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur un entretien d'embauche pour un petit boulot.",
    texteFR: ["Hier, Emma a passé un entretien pour travailler dans une boulangerie pendant les vacances.", "Le gérant lui a demandé pourquoi elle voulait ce poste et si elle avait déjà de l'expérience.", "Emma a répondu qu'elle aimait le contact avec les clients et qu'elle était toujours ponctuelle.", "À la fin de l'entretien, le gérant lui a dit qu'il la rappellerait dans quelques jours.", "Emma est repartie confiante, même si elle savait que d'autres candidats avaient postulé."],
    texteLangue: ["Yesterday, Emma had an interview to work in a bakery during the holidays.", "The manager asked her why she wanted this job and whether she already had experience.", "Emma answered that she liked being in contact with customers and that she was always on time.", "At the end of the interview, the manager told her he would call her back in a few days.", "Emma left feeling confident, even though she knew other candidates had applied."],
    vocabulaireAide: [{ mot: "passer un entretien", traduction: "to have an interview" }, { mot: "le gérant", traduction: "the manager" }, { mot: "ponctuel", traduction: "on time / punctual" }, { mot: "rappeler quelqu'un", traduction: "to call somebody back" }, { mot: "postuler", traduction: "to apply" }],
    pointsAttention: ["« Avoir de l'expérience » se traduit par « to have experience », sans article devant « experience ».", "Le discours indirect au passé entraîne une concordance des temps : « elle a dit qu'elle aimait » → « she said (that) she liked »."],
  },
  {
    slug: "environnement-durable-traduction-anglais-4e",
    titre: "Agir pour l'environnement / Acting for the environment",
    matiere: "anglais",
    niveau: "4e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur les gestes écologiques du quotidien.",
    texteFR: ["De plus en plus de jeunes essaient de réduire leurs déchets et de consommer de façon plus responsable.", "Au collège de Léo, une association a été créée pour sensibiliser les élèves au tri sélectif.", "Chaque semaine, des volontaires ramassent les déchets plastiques trouvés près de la rivière.", "Léo pense que si chacun changeait une petite habitude, cela aurait un grand impact sur la planète.", "Il espère que d'autres collèges suivront cet exemple dans les années à venir."],
    texteLangue: ["More and more young people are trying to reduce their waste and to consume more responsibly.", "At Léo's school, an association was created to raise students' awareness about recycling.", "Every week, volunteers pick up plastic waste found near the river.", "Léo thinks that if everyone changed one small habit, it would have a big impact on the planet.", "He hopes that other schools will follow this example in the years to come."],
    vocabulaireAide: [{ mot: "réduire", traduction: "to reduce" }, { mot: "les déchets", traduction: "waste" }, { mot: "le tri sélectif", traduction: "recycling / waste sorting" }, { mot: "ramasser", traduction: "to pick up" }, { mot: "sensibiliser", traduction: "to raise awareness" }],
    pointsAttention: ["La structure « if + prétérit, would + base verbale » sert à exprimer une hypothèse : « si chacun changeait... cela aurait » → « if everyone changed... it would have ».", "« Les années à venir » se traduit par « the years to come », expression figée à connaître."],
  },
  {
    slug: "reseaux-sociaux-traduction-anglais-4e",
    titre: "Les réseaux sociaux et les jeunes / Social media and young people",
    matiere: "anglais",
    niveau: "4e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte argumentatif sur l'usage des réseaux sociaux.",
    texteFR: ["Beaucoup d'adolescents passent plusieurs heures par jour sur les réseaux sociaux.", "Certains parents pensent que cette habitude est dangereuse pour la concentration et le sommeil.", "D'autres estiment que ces plateformes permettent aussi de rester en contact avec des amis éloignés.", "Les spécialistes conseillent de limiter le temps d'écran et de privilégier les échanges en face à face.", "La question reste débattue, mais tout le monde s'accorde sur l'importance d'un usage raisonné."],
    texteLangue: ["Many teenagers spend several hours a day on social media.", "Some parents think that this habit is dangerous for concentration and sleep.", "Others believe that these platforms also allow people to stay in touch with faraway friends.", "Experts recommend limiting screen time and favouring face-to-face conversations.", "The question remains debated, but everyone agrees on the importance of reasonable use."],
    vocabulaireAide: [{ mot: "les réseaux sociaux", traduction: "social media" }, { mot: "le sommeil", traduction: "sleep" }, { mot: "rester en contact", traduction: "to stay in touch" }, { mot: "le temps d'écran", traduction: "screen time" }, { mot: "s'accorder sur", traduction: "to agree on" }],
    pointsAttention: ["« Passer du temps à faire quelque chose » se traduit par « to spend time doing something », avec le verbe en -ing.", "Attention au faux-ami « estimer » (= to believe/to think), qui ne signifie pas « to estimate » dans ce contexte."],
  },
  {
    slug: "choix-orientation-traduction-anglais-3e",
    titre: "Choisir son orientation / Choosing a career path",
    matiere: "anglais",
    niveau: "3e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur les choix d'orientation en fin de troisième.",
    texteFR: ["À la fin de la troisième, les élèves doivent choisir entre plusieurs voies : le lycée général, technologique ou professionnel.", "Sami hésite encore, car il aime autant les sciences que les langues étrangères.", "Ses professeurs lui ont conseillé de participer à des stages pour découvrir différents métiers.", "S'il avait su plus tôt ce qu'il voulait faire, il se serait senti moins stressé pendant cette période.", "Finalement, il a décidé de suivre un baccalauréat général avec option sciences, tout en continuant l'anglais renforcé.", "Il sait que ce choix n'est pas définitif et qu'il pourra encore changer d'avis plus tard."],
    texteLangue: ["At the end of Year 10 (troisième), students have to choose between several paths: general, technological or vocational high school.", "Sami is still hesitating, because he likes science as much as foreign languages.", "His teachers advised him to take part in work placements to discover different jobs.", "If he had known earlier what he wanted to do, he would have felt less stressed during that period.", "In the end, he decided to follow a general baccalaureate with a science option, while continuing advanced English.", "He knows that this choice is not final and that he will still be able to change his mind later."],
    vocabulaireAide: [{ mot: "l'orientation", traduction: "career guidance / career path" }, { mot: "un stage", traduction: "a work placement" }, { mot: "stressé", traduction: "stressed" }, { mot: "définitif", traduction: "final" }, { mot: "changer d'avis", traduction: "to change one's mind" }],
    pointsAttention: ["Le troisième conditionnel (« if he had known... he would have felt ») exprime un regret ou une hypothèse irréelle dans le passé.", "« Autant... que » se traduit par « as much... as » : « il aime autant les sciences que les langues » → « he likes science as much as languages »."],
  },
  {
    slug: "depart-etranger-traduction-anglais-3e",
    titre: "Partir vivre à l'étranger / Moving abroad",
    matiere: "anglais",
    niveau: "3e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur une expérience de mobilité internationale.",
    texteFR: ["Quand ses parents lui ont annoncé qu'ils allaient déménager au Canada, Chloé a d'abord été bouleversée.", "Elle devait quitter ses amis, son collège et tout ce qu'elle connaissait depuis toujours.", "Peu à peu, elle a commencé à s'intéresser à la culture canadienne et à améliorer son anglais.", "Si elle n'avait pas eu cette occasion, elle n'aurait jamais découvert d'autres façons de vivre.", "Aujourd'hui, même si le pays lui manque parfois, elle est fière d'avoir su s'adapter.", "Elle pense que cette expérience l'a rendue plus indépendante et plus ouverte d'esprit."],
    texteLangue: ["When her parents told her they were going to move to Canada, Chloé was upset at first.", "She had to leave her friends, her school and everything she had always known.", "Little by little, she started to take an interest in Canadian culture and to improve her English.", "If she hadn't had this opportunity, she would never have discovered other ways of living.", "Today, even though she sometimes misses her country, she is proud to have managed to adapt.", "She thinks that this experience has made her more independent and more open-minded."],
    vocabulaireAide: [{ mot: "déménager", traduction: "to move house" }, { mot: "bouleversé", traduction: "upset" }, { mot: "peu à peu", traduction: "little by little" }, { mot: "s'adapter", traduction: "to adapt" }, { mot: "ouvert d'esprit", traduction: "open-minded" }],
    pointsAttention: ["« Manquer à quelqu'un » se traduit en anglais par une construction inversée : « le pays lui manque » → « she misses the country ».", "Le verbe « miss » se construit directement avec un complément, sans préposition."],
  },
  {
    slug: "engagement-benevolat-traduction-anglais-3e",
    titre: "S'engager comme bénévole / Volunteering",
    matiere: "anglais",
    niveau: "3e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur l'engagement citoyen des adolescents.",
    texteFR: ["De plus en plus de collégiens choisissent de donner de leur temps pour aider les autres.", "Nora, par exemple, est bénévole chaque week-end dans une association qui distribue des repas.", "Elle affirme que cette expérience lui a appris à être plus patiente et plus attentive aux autres.", "Si elle continue ainsi, elle espère un jour travailler dans le secteur humanitaire.", "Ses amis, impressionnés par son engagement, ont décidé de la rejoindre le mois prochain.", "Pour Nora, être bénévole n'est pas une contrainte mais une façon de se sentir utile."],
    texteLangue: ["More and more middle-school students choose to give up their time to help others.", "Nora, for example, volunteers every weekend for an association that distributes meals.", "She says that this experience has taught her to be more patient and more attentive to others.", "If she carries on like this, she hopes to work in the humanitarian sector one day.", "Her friends, impressed by her commitment, decided to join her next month.", "For Nora, volunteering is not a constraint but a way of feeling useful."],
    vocabulaireAide: [{ mot: "bénévole", traduction: "volunteer" }, { mot: "distribuer", traduction: "to distribute" }, { mot: "l'engagement", traduction: "commitment" }, { mot: "le secteur humanitaire", traduction: "the humanitarian sector" }, { mot: "impressionné", traduction: "impressed" }],
    pointsAttention: ["« Donner de son temps » se traduit par « to give up one's time », avec la particule « up ».", "« Une façon de se sentir utile » se traduit par « a way of feeling useful », avec le verbe en -ing après « of »."],
  },
  {
    slug: "entrevista-trabajo-traduccion-espagnol-4e",
    titre: "Una entrevista de trabajo / Un entretien d'embauche",
    matiere: "espagnol",
    niveau: "4e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur un entretien pour un job d'été.",
    texteFR: ["Ayer, Marta tuvo una entrevista para trabajar en una panadería durante las vacaciones.", "El encargado le preguntó por qué quería ese puesto y si ya tenía experiencia.", "Marta contestó que le gustaba el contacto con los clientes y que siempre era puntual.", "Al final de la entrevista, el encargado le dijo que la llamaría en unos días.", "Marta se fue confiada, aunque sabía que otros candidatos también se habían presentado."],
    texteLangue: ["Hier, Marta a passé un entretien pour travailler dans une boulangerie pendant les vacances.", "L'encargado lui a demandé pourquoi elle voulait ce poste et si elle avait déjà de l'expérience.", "Marta a répondu qu'elle aimait le contact avec les clients et qu'elle était toujours ponctuelle.", "À la fin de l'entretien, le gérant lui a dit qu'il l'appellerait dans quelques jours.", "Marta est repartie confiante, même si elle savait que d'autres candidats s'étaient aussi présentés."],
    vocabulaireAide: [{ mot: "la entrevista", traduction: "l'entretien" }, { mot: "el encargado", traduction: "le gérant / le responsable" }, { mot: "puntual", traduction: "ponctuel" }, { mot: "contestar", traduction: "répondre" }, { mot: "presentarse", traduction: "se présenter / postuler" }],
    pointsAttention: ["Le style indirect en espagnol garde souvent l'imparfait après un verbe au passé : « dijo que la llamaría » (conditionnel).", "Attention au faux-ami « contestar » qui signifie « répondre » et non « contester »."],
  },
  {
    slug: "medio-ambiente-traduccion-espagnol-4e",
    titre: "Actuar por el medio ambiente / Agir pour l'environnement",
    matiere: "espagnol",
    niveau: "4e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur les gestes écologiques du quotidien.",
    texteFR: ["Cada vez más jóvenes intentan reducir su basura y consumir de forma más responsable.", "En el colegio de Diego, se creó una asociación para concienciar a los alumnos sobre el reciclaje.", "Cada semana, voluntarios recogen los plásticos que encuentran cerca del río.", "Diego piensa que si cada uno cambiara un pequeño hábito, eso tendría un gran impacto en el planeta.", "Espera que otros colegios sigan este ejemplo en los próximos años."],
    texteLangue: ["De plus en plus de jeunes essaient de réduire leurs déchets et de consommer de façon plus responsable.", "Au collège de Diego, une association a été créée pour sensibiliser les élèves au recyclage.", "Chaque semaine, des volontaires ramassent les plastiques trouvés près de la rivière.", "Diego pense que si chacun changeait une petite habitude, cela aurait un grand impact sur la planète.", "Il espère que d'autres collèges suivront cet exemple dans les années à venir."],
    vocabulaireAide: [{ mot: "la basura", traduction: "les déchets" }, { mot: "concienciar", traduction: "sensibiliser" }, { mot: "reciclaje", traduction: "le recyclage" }, { mot: "recoger", traduction: "ramasser" }, { mot: "el impacto", traduction: "l'impact" }],
    pointsAttention: ["Le subjonctif imparfait après « si » (« si cada uno cambiara ») correspond à l'imparfait français dans une hypothèse : « si chacun changeait ».", "« Los próximos años » se traduit par « les années à venir » ou « les prochaines années »."],
  },
  {
    slug: "redes-sociales-traduccion-espagnol-4e",
    titre: "Las redes sociales y los jóvenes / Les réseaux sociaux et les jeunes",
    matiere: "espagnol",
    niveau: "4e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte argumentatif sur l'usage des réseaux sociaux.",
    texteFR: ["Muchos adolescentes pasan varias horas al día en las redes sociales.", "Algunos padres piensan que este hábito es peligroso para la concentración y el sueño.", "Otros creen que estas plataformas también permiten mantener el contacto con amigos lejanos.", "Los expertos aconsejan limitar el tiempo de pantalla y priorizar las conversaciones cara a cara.", "El debate sigue abierto, pero todos coinciden en la importancia de un uso razonable."],
    texteLangue: ["Beaucoup d'adolescents passent plusieurs heures par jour sur les réseaux sociaux.", "Certains parents pensent que cette habitude est dangereuse pour la concentration et le sommeil.", "D'autres pensent que ces plateformes permettent aussi de rester en contact avec des amis éloignés.", "Les experts conseillent de limiter le temps d'écran et de privilégier les échanges en face à face.", "Le débat reste ouvert, mais tout le monde s'accorde sur l'importance d'un usage raisonnable."],
    vocabulaireAide: [{ mot: "las redes sociales", traduction: "les réseaux sociaux" }, { mot: "el sueño", traduction: "le sommeil" }, { mot: "mantener el contacto", traduction: "rester en contact" }, { mot: "el tiempo de pantalla", traduction: "le temps d'écran" }, { mot: "coincidir en", traduction: "s'accorder sur" }],
    pointsAttention: ["« Pasar tiempo haciendo algo » se traduit par « passer du temps à faire quelque chose », avec le gérondif espagnol.", "« Cara a cara » se traduit littéralement par « face à face »."],
  },
  {
    slug: "eleccion-orientacion-traduccion-espagnol-3e",
    titre: "Elegir su orientación / Choisir son orientation",
    matiere: "espagnol",
    niveau: "3e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur les choix d'orientation en fin de troisième.",
    texteFR: ["Al final de la ESO, los alumnos deben elegir entre varias vías: el bachillerato general, tecnológico o la formación profesional.", "Sara todavía duda, porque le gustan tanto las ciencias como los idiomas extranjeros.", "Sus profesores le aconsejaron hacer prácticas para descubrir distintos oficios.", "Si hubiera sabido antes lo que quería hacer, se habría sentido menos estresada durante ese período.", "Al final, decidió seguir un bachillerato de ciencias, continuando además con el inglés avanzado.", "Sabe que esta elección no es definitiva y que todavía podrá cambiar de opinión más adelante."],
    texteLangue: ["À la fin de la troisième, les élèves doivent choisir entre plusieurs voies : le lycée général, technologique ou professionnel.", "Sara hésite encore, car elle aime autant les sciences que les langues étrangères.", "Ses professeurs lui ont conseillé de faire des stages pour découvrir différents métiers.", "Si elle avait su plus tôt ce qu'elle voulait faire, elle se serait sentie moins stressée pendant cette période.", "Finalement, elle a décidé de suivre un baccalauréat scientifique, en continuant aussi l'anglais avancé.", "Elle sait que ce choix n'est pas définitif et qu'elle pourra encore changer d'avis plus tard."],
    vocabulaireAide: [{ mot: "la orientación", traduction: "l'orientation" }, { mot: "las prácticas", traduction: "les stages" }, { mot: "estresado", traduction: "stressé" }, { mot: "definitivo", traduction: "définitif" }, { mot: "cambiar de opinión", traduction: "changer d'avis" }],
    pointsAttention: ["Le plus-que-parfait du subjonctif (« si hubiera sabido... se habría sentido ») exprime un regret ou une hypothèse irréelle dans le passé, équivalent au 3e conditionnel français.", "« Tanto... como » se traduit par « autant... que » : « le gustan tanto las ciencias como los idiomas » → « elle aime autant les sciences que les langues »."],
  },
  {
    slug: "mudanza-extranjero-traduccion-espagnol-3e",
    titre: "Irse a vivir al extranjero / Partir vivre à l'étranger",
    matiere: "espagnol",
    niveau: "3e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur une expérience de mobilité internationale.",
    texteFR: ["Cuando sus padres le anunciaron que se mudaban a México, Valentina se quedó desconcertada al principio.", "Tenía que dejar a sus amigos, su colegio y todo lo que había conocido siempre.", "Poco a poco, empezó a interesarse por la cultura mexicana y a mejorar su español.", "Si no hubiera tenido esta oportunidad, nunca habría descubierto otras formas de vivir.", "Hoy en día, aunque a veces echa de menos su país, está orgullosa de haber sabido adaptarse.", "Piensa que esta experiencia la ha hecho más independiente y más abierta de mente."],
    texteLangue: ["Quand ses parents lui ont annoncé qu'ils déménageaient au Mexique, Valentina a d'abord été déconcertée.", "Elle devait quitter ses amis, son collège et tout ce qu'elle avait toujours connu.", "Peu à peu, elle a commencé à s'intéresser à la culture mexicaine et à améliorer son espagnol.", "Si elle n'avait pas eu cette occasion, elle n'aurait jamais découvert d'autres façons de vivre.", "Aujourd'hui, même si son pays lui manque parfois, elle est fière d'avoir su s'adapter.", "Elle pense que cette expérience l'a rendue plus indépendante et plus ouverte d'esprit."],
    vocabulaireAide: [{ mot: "mudarse", traduction: "déménager" }, { mot: "desconcertado", traduction: "déconcerté" }, { mot: "poco a poco", traduction: "peu à peu" }, { mot: "adaptarse", traduction: "s'adapter" }, { mot: "echar de menos", traduction: "manquer à / regretter" }],
    pointsAttention: ["« Echar de menos » est l'expression espagnole pour « manquer à quelqu'un » : « echa de menos su país » → « son pays lui manque ».", "Le subjonctif plus-que-parfait après « si » exprime une hypothèse irréelle dans le passé, comme en français."],
  },
  {
    slug: "voluntariado-traduccion-espagnol-3e",
    titre: "Ser voluntario / S'engager comme bénévole",
    matiere: "espagnol",
    niveau: "3e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur l'engagement citoyen des adolescents.",
    texteFR: ["Cada vez más estudiantes deciden dar su tiempo para ayudar a los demás.", "Lucía, por ejemplo, es voluntaria cada fin de semana en una asociación que reparte comida.", "Ella afirma que esta experiencia le ha enseñado a ser más paciente y más atenta a los demás.", "Si sigue así, espera algún día trabajar en el sector humanitario.", "Sus amigos, impresionados por su compromiso, decidieron unirse a ella el mes que viene.", "Para Lucía, ser voluntaria no es una obligación sino una forma de sentirse útil."],
    texteLangue: ["De plus en plus d'élèves décident de donner de leur temps pour aider les autres.", "Lucía, par exemple, est bénévole chaque week-end dans une association qui distribue des repas.", "Elle affirme que cette expérience lui a appris à être plus patiente et plus attentive aux autres.", "Si elle continue ainsi, elle espère un jour travailler dans le secteur humanitaire.", "Ses amis, impressionnés par son engagement, ont décidé de la rejoindre le mois prochain.", "Pour Lucía, être bénévole n'est pas une obligation mais une façon de se sentir utile."],
    vocabulaireAide: [{ mot: "voluntario", traduction: "bénévole" }, { mot: "repartir", traduction: "distribuer" }, { mot: "el compromiso", traduction: "l'engagement" }, { mot: "el sector humanitario", traduction: "le secteur humanitaire" }, { mot: "impresionado", traduction: "impressionné" }],
    pointsAttention: ["« El mes que viene » se traduit par « le mois prochain ».", "« Una forma de sentirse útil » se traduit par « une façon de se sentir utile »."],
  },
  {
    slug: "colloquio-lavoro-traduzione-italien-4e",
    titre: "Un colloquio di lavoro / Un entretien d'embauche",
    matiere: "italien",
    niveau: "4e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur un entretien pour un job d'été.",
    texteFR: ["Ieri, Giulia ha avuto un colloquio per lavorare in una panetteria durante le vacanze.", "Il titolare le ha chiesto perché volesse quel posto e se avesse già esperienza.", "Giulia ha risposto che le piaceva il contatto con i clienti e che era sempre puntuale.", "Alla fine del colloquio, il titolare le ha detto che l'avrebbe richiamata tra qualche giorno.", "Giulia è tornata a casa fiduciosa, anche se sapeva che altri candidati si erano presentati."],
    texteLangue: ["Hier, Giulia a passé un entretien pour travailler dans une boulangerie pendant les vacances.", "Le patron lui a demandé pourquoi elle voulait ce poste et si elle avait déjà de l'expérience.", "Giulia a répondu qu'elle aimait le contact avec les clients et qu'elle était toujours ponctuelle.", "À la fin de l'entretien, le patron lui a dit qu'il la rappellerait dans quelques jours.", "Giulia est repartie confiante, même si elle savait que d'autres candidats s'étaient aussi présentés."],
    vocabulaireAide: [{ mot: "il colloquio", traduction: "l'entretien" }, { mot: "il titolare", traduction: "le patron" }, { mot: "puntuale", traduction: "ponctuel" }, { mot: "richiamare", traduction: "rappeler" }, { mot: "presentarsi", traduction: "se présenter / postuler" }],
    pointsAttention: ["Le conditionnel passé italien (« avrebbe richiamata ») correspond au futur dans le passé français : « il la rappellerait ».", "Attention à l'accord du participe passé avec le pronom complément : « l'avrebbe richiamata » (fém.)."],
  },
  {
    slug: "ambiente-sostenibile-traduzione-italien-4e",
    titre: "Agire per l'ambiente / Agir pour l'environnement",
    matiere: "italien",
    niveau: "4e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur les gestes écologiques du quotidien.",
    texteFR: ["Sempre più giovani cercano di ridurre i propri rifiuti e di consumare in modo più responsabile.", "Nella scuola di Marco è stata creata un'associazione per sensibilizzare gli alunni alla raccolta differenziata.", "Ogni settimana, dei volontari raccolgono la plastica trovata vicino al fiume.", "Marco pensa che se ognuno cambiasse una piccola abitudine, questo avrebbe un grande impatto sul pianeta.", "Spera che altre scuole seguano questo esempio nei prossimi anni."],
    texteLangue: ["De plus en plus de jeunes essaient de réduire leurs déchets et de consommer de façon plus responsable.", "Dans l'école de Marco, une association a été créée pour sensibiliser les élèves au tri sélectif.", "Chaque semaine, des volontaires ramassent le plastique trouvé près de la rivière.", "Marco pense que si chacun changeait une petite habitude, cela aurait un grand impact sur la planète.", "Il espère que d'autres écoles suivront cet exemple dans les prochaines années."],
    vocabulaireAide: [{ mot: "i rifiuti", traduction: "les déchets" }, { mot: "sensibilizzare", traduction: "sensibiliser" }, { mot: "la raccolta differenziata", traduction: "le tri sélectif" }, { mot: "raccogliere", traduction: "ramasser" }, { mot: "l'impatto", traduction: "l'impact" }],
    pointsAttention: ["Le périod hypothétique italien « se + congiuntivo imperfetto, condizionale » correspond à « si + imparfait, conditionnel » en français.", "« Nei prossimi anni » se traduit par « dans les prochaines années » ou « dans les années à venir »."],
  },
  {
    slug: "social-media-traduzione-italien-4e",
    titre: "I social media e i giovani / Les réseaux sociaux et les jeunes",
    matiere: "italien",
    niveau: "4e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte argumentatif sur l'usage des réseaux sociaux.",
    texteFR: ["Molti adolescenti passano diverse ore al giorno sui social media.", "Alcuni genitori pensano che questa abitudine sia pericolosa per la concentrazione e il sonno.", "Altri credono che queste piattaforme permettano anche di restare in contatto con amici lontani.", "Gli esperti consigliano di limitare il tempo davanti allo schermo e di privilegiare gli incontri di persona.", "Il dibattito resta aperto, ma tutti concordano sull'importanza di un uso ragionevole."],
    texteLangue: ["Beaucoup d'adolescents passent plusieurs heures par jour sur les réseaux sociaux.", "Certains parents pensent que cette habitude est dangereuse pour la concentration et le sommeil.", "D'autres pensent que ces plateformes permettent aussi de rester en contact avec des amis éloignés.", "Les experts conseillent de limiter le temps d'écran et de privilégier les rencontres en personne.", "Le débat reste ouvert, mais tout le monde s'accorde sur l'importance d'un usage raisonnable."],
    vocabulaireAide: [{ mot: "i social media", traduction: "les réseaux sociaux" }, { mot: "il sonno", traduction: "le sommeil" }, { mot: "restare in contatto", traduction: "rester en contact" }, { mot: "lo schermo", traduction: "l'écran" }, { mot: "concordare su", traduction: "s'accorder sur" }],
    pointsAttention: ["Le subjonctif italien après « pensare che » (« sia pericolosa ») ne se traduit pas littéralement en français, qui utilise l'indicatif après « penser que » à la forme affirmative.", "« Di persona » se traduit par « en personne » ou « en face à face »."],
  },
  {
    slug: "scelta-orientamento-traduzione-italien-3e",
    titre: "Scegliere il proprio orientamento / Choisir son orientation",
    matiere: "italien",
    niveau: "3e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur les choix d'orientation en fin de troisième.",
    texteFR: ["Alla fine della terza media, gli studenti devono scegliere tra diversi indirizzi: liceo, istituto tecnico o professionale.", "Sara è ancora indecisa, perché le piacciono tanto le scienze quanto le lingue straniere.", "I suoi professori le hanno consigliato di fare degli stage per scoprire mestieri diversi.", "Se avesse saputo prima cosa voleva fare, si sarebbe sentita meno stressata durante quel periodo.", "Alla fine, ha deciso di seguire un liceo scientifico, continuando anche l'inglese avanzato.", "Sa che questa scelta non è definitiva e che potrà ancora cambiare idea più avanti."],
    texteLangue: ["À la fin de la troisième, les élèves doivent choisir entre plusieurs voies : lycée général, technologique ou professionnel.", "Sara hésite encore, car elle aime autant les sciences que les langues étrangères.", "Ses professeurs lui ont conseillé de faire des stages pour découvrir différents métiers.", "Si elle avait su plus tôt ce qu'elle voulait faire, elle se serait sentie moins stressée pendant cette période.", "Finalement, elle a décidé de suivre un lycée scientifique, en continuant aussi l'anglais avancé.", "Elle sait que ce choix n'est pas définitif et qu'elle pourra encore changer d'avis plus tard."],
    vocabulaireAide: [{ mot: "l'orientamento", traduction: "l'orientation" }, { mot: "lo stage", traduction: "le stage" }, { mot: "stressato", traduction: "stressé" }, { mot: "definitivo", traduction: "définitif" }, { mot: "cambiare idea", traduction: "changer d'avis" }],
    pointsAttention: ["Le périod hypothétique du 2e type au passé (« se avesse saputo... si sarebbe sentita ») correspond au 3e conditionnel français.", "« Tanto... quanto » se traduit par « autant... que » : « le piacciono tanto le scienze quanto le lingue » → « elle aime autant les sciences que les langues »."],
  },
  {
    slug: "trasferimento-estero-traduzione-italien-3e",
    titre: "Andare a vivere all'estero / Partir vivre à l'étranger",
    matiere: "italien",
    niveau: "3e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur une expérience de mobilité internationale.",
    texteFR: ["Quando i suoi genitori le annunciarono che si sarebbero trasferiti in Germania, Chiara rimase sconvolta all'inizio.", "Doveva lasciare i suoi amici, la sua scuola e tutto ciò che aveva sempre conosciuto.", "Poco a poco, cominciò a interessarsi alla cultura tedesca e a migliorare il suo inglese.", "Se non avesse avuto questa occasione, non avrebbe mai scoperto altri modi di vivere.", "Oggi, anche se a volte le manca il suo paese, è fiera di essere riuscita ad adattarsi.", "Pensa che questa esperienza l'abbia resa più indipendente e più aperta mentalmente."],
    texteLangue: ["Quand ses parents lui ont annoncé qu'ils allaient déménager en Allemagne, Chiara a d'abord été bouleversée.", "Elle devait quitter ses amis, son école et tout ce qu'elle avait toujours connu.", "Peu à peu, elle a commencé à s'intéresser à la culture allemande et à améliorer son anglais.", "Si elle n'avait pas eu cette occasion, elle n'aurait jamais découvert d'autres façons de vivre.", "Aujourd'hui, même si son pays lui manque parfois, elle est fière d'avoir su s'adapter.", "Elle pense que cette expérience l'a rendue plus indépendante et plus ouverte d'esprit."],
    vocabulaireAide: [{ mot: "trasferirsi", traduction: "déménager" }, { mot: "sconvolto", traduction: "bouleversé" }, { mot: "poco a poco", traduction: "peu à peu" }, { mot: "adattarsi", traduction: "s'adapter" }, { mot: "mancare a qualcuno", traduction: "manquer à quelqu'un" }],
    pointsAttention: ["« Mancare a qualcuno » fonctionne comme en français : « le manca il suo paese » → « son pays lui manque » (construction inversée).", "Le subjonctif imparfait après « se » exprime une hypothèse irréelle : « se non avesse avuto » → « si elle n'avait pas eu »."],
  },
  {
    slug: "volontariato-traduzione-italien-3e",
    titre: "Fare volontariato / S'engager comme bénévole",
    matiere: "italien",
    niveau: "3e",
    niveauCECRL: "B1",
    duree: "20 min",
    resume: "S'entraîner à traduire un texte sur l'engagement citoyen des adolescents.",
    texteFR: ["Sempre più studenti decidono di dedicare il proprio tempo per aiutare gli altri.", "Elena, per esempio, fa volontariato ogni fine settimana in un'associazione che distribuisce pasti.", "Lei afferma che questa esperienza le ha insegnato a essere più paziente e più attenta agli altri.", "Se continua così, spera un giorno di lavorare nel settore umanitario.", "I suoi amici, colpiti dal suo impegno, hanno deciso di unirsi a lei il mese prossimo.", "Per Elena, fare volontariato non è un obbligo ma un modo per sentirsi utile."],
    texteLangue: ["De plus en plus d'élèves décident de donner de leur temps pour aider les autres.", "Elena, par exemple, est bénévole chaque week-end dans une association qui distribue des repas.", "Elle affirme que cette expérience lui a appris à être plus patiente et plus attentive aux autres.", "Si elle continue ainsi, elle espère un jour travailler dans le secteur humanitaire.", "Ses amis, touchés par son engagement, ont décidé de la rejoindre le mois prochain.", "Pour Elena, être bénévole n'est pas une obligation mais une façon de se sentir utile."],
    vocabulaireAide: [{ mot: "il volontariato", traduction: "le bénévolat" }, { mot: "distribuire", traduction: "distribuer" }, { mot: "l'impegno", traduction: "l'engagement" }, { mot: "il settore umanitario", traduction: "le secteur humanitaire" }, { mot: "colpito", traduction: "touché / impressionné" }],
    pointsAttention: ["« Il mese prossimo » se traduit par « le mois prochain ».", "« Un modo per sentirsi utile » se traduit par « une façon de se sentir utile »."],
  },
];

export function textesTraduction(matiere: string, niveau: string) {
  return TEXTES_TRADUCTION.filter((t) => t.matiere === matiere && t.niveau === niveau);
}

export function texteTraductionBySlug(slug: string) {
  return TEXTES_TRADUCTION.find((t) => t.slug === slug);
}
